logging.config=classpath:logback-base.xml

spring.application.name=PN-PAPER-EVENT-ENRICHER-MS

# Runtime mode
pn.env.runtime=PROD

pn.paper-event-enricher.sqs.paper-archives-queue-name=${PN_PAPEREVENTENRICHER_SQS_PAPERARCHIVESQUEUENAME}
pn.paper-event-enricher.sqs.paper-event-enrichment-input-queue-name=${PN_PAPEREVENTENRICHER_SQS_PAPEREVENTENRICHMENTINPUTQUEUENAME}

sqs.listener.paper-input.max-concurrent-messages=1
sqs.listener.paper-input.max-messages-per-poll=10
sqs.listener.paper-input.poll-timeout=10h

spring.cloud.aws.sqs.paperInputConsumer.max-concurrent-messages=${PN_PAPEREVENTENRICHER_SQS_INPUTQUEUECONCURRENCY}
spring.cloud.aws.sqs.paperInputConsumer.max-messages-per-poll=${PN_PAPEREVENTENRICHER_SQS_INPUTQUEUEMAXNUMBEROFMESSAGES}
spring.cloud.aws.sqs.paperArchiveConsumer.max-concurrent-messages=${PN_PAPEREVENTENRICHER_SQS_ARCHIVEQUEUECONCURRENCY}
spring.cloud.aws.sqs.paperArchiveConsumer.poll-timeout-seconds=${PN_PAPEREVENTENRICHER_ARCHIVEQUEUESTOPTIMEOUT}
spring.cloud.aws.sqs.paperArchiveConsumer.max-messages-per-poll=${PN_PAPEREVENTENRICHER_SQS_ARCHIVEQUEUEMAXNUMBEROFMESSAGES}

pn.paper-event-enricher.pdf-page-size=2
