logging.config=config/logback-local.xml
server.port=8091

# Runtime mode
pn.env.runtime=DEVELOPMENT

pn.paper-event-enricher.safe-storage-base-url=http://localhost:8887
pn.paper-event-enricher.cx-id=pn-paper-event-enricher

pn.paper-event-enricher.dao.paper-event-enrichment-table=pn-PaperChannelEventEnrichment
pn.paper-event-enricher.sqs.paper-archives-queue-name=pn-paper-archives
pn.paper-event-enricher.sqs.paper-event-enrichment-input-queue-name=pn-paper-event-enrichment-input

pn.paper-event-enricher.safestorage-connection-timeout-millis=20000
pn.paper-event-enricher.safestorage-read-timeout-millis=20000
pn.paper-event-enricher.safe-storage-upload-max-concurrent-request=10
pn.paper-event-enricher.update-item-max-concurrent-request=100

pn.paper-event-enricher.pdf-two-pages-enabled=true

#decommentare le props aws. e cloud.aws quando si avvia il microservizio in locale
aws.region-code=us-east-1
aws.endpoint-url=http://localhost:4566

# application-local.properties
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# Disabilita la creazione automatica se la coda non esiste
spring.cloud.aws.sqs.enabled=true

sqs.listener.paper-input.max-concurrent-messages=1
sqs.listener.paper-input.max-messages-per-poll=10
sqs.listener.paper-input.poll-timeout=10h

spring.cloud.aws.sqs.paperInputConsumer.max-concurrent-messages=1
spring.cloud.aws.sqs.paperInputConsumer.max-messages-per-poll=1
spring.cloud.aws.sqs.paperArchiveConsumer.max-concurrent-messages=1
spring.cloud.aws.sqs.paperArchiveConsumer.poll-timeout-seconds=3600
spring.cloud.aws.sqs.paperArchiveConsumer.max-messages-per-poll=1

