logging.config=config/logback-local.xml
server.port=8091

# Runtime mode
pn.env.runtime=DEVELOPMENT

pn.paper-event-enricher.safe-storage-base-url=http://localhost:8887
pn.paper-event-enricher.cx-id=pn-paper-event-enricher

pn.paper-event-enricher.dao.paper-event-enrichment-table=pn-PaperChannelEventEnrichment
pn.paper-event-enricher.sqs.paper-archives-queue-name=pn-paper-archives
pn.paper-event-enricher.sqs.paper-event-enrichment-input-queue-name=pn-paper-event-enrichment-input
pn.paper-event-enricher.sqs.safe-storage-to-paper-event-enricher-queue-name=pn-safe-storage-to-paper-event-enricher
pn.paper-event-enricher.safestorage-connection-timeout-millis=20000
pn.paper-event-enricher.safestorage-read-timeout-millis=20000
pn.paper-event-enricher.safe-storage-upload-max-concurrent-request=10
pn.paper-event-enricher.update-item-max-concurrent-request=100

pn.paper-event-enricher.pdf-two-pages-enabled=true


aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.region-code=us-east-1
aws.endpoint-url=http://localhost:4566

# application-local.properties
spring.cloud.aws.credentials.profile.name=${aws.profile-name}
spring.cloud.aws.region.static=${aws.region-code}
spring.cloud.aws.sqs.endpoint=${aws.endpoint-url}


pn.paper-event-enricher.sqs.input-queue-concurrency=10
pn.paper-event-enricher.sqs.input-queue-max-number-of-messages=10
pn.paper-event-enricher.sqs.archive-queue-concurrency=1
pn.paper-event-enricher.sqs.archive-queue-max-number-of-messages=1
pn.paper-event-enricher.sqs.archive-queue-stop-timeout=36000

